# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5425832384795ada7a34f81a2f77e20a20801363d8e8ff993273503163f98a4d10b77ebe5c41002644d61b063d1eb07f0db6e9f4d93de4c0fda29c3e0790f4d4

test:
  secret_key_base: 950335569a604a42c2efef22f2160a965af031133a6c387d5889d06b0e4f2566d206f126a7aec2ed5881a3293fc1497acfb90dbc5b2d553bf15847dbae1c60f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
